/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Day = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const VerificationMode = IDL.Variant({
  'mathPuzzle' : IDL.Null,
  'selfie' : IDL.Null,
  'voicePrompt' : IDL.Null,
});
export const Alarm = IDL.Record({
  'id' : IDL.Nat,
  'repeatDays' : IDL.Vec(Day),
  'verificationMode' : VerificationMode,
  'time' : Time,
  'enabled' : IDL.Bool,
  'sound' : IDL.Text,
});
export const UserStats = IDL.Record({
  'totalSuccesses' : IDL.Nat,
  'lastSuccessDate' : Time,
  'currentStreak' : IDL.Nat,
  'totalAlarmsTriggered' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAlarm' : IDL.Func(
      [Time, IDL.Vec(Day), VerificationMode, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAlarm' : IDL.Func([IDL.Nat], [], []),
  'getAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
  'getStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
  'updateAlarm' : IDL.Func(
      [IDL.Nat, Time, IDL.Vec(Day), VerificationMode, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Day = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const VerificationMode = IDL.Variant({
    'mathPuzzle' : IDL.Null,
    'selfie' : IDL.Null,
    'voicePrompt' : IDL.Null,
  });
  const Alarm = IDL.Record({
    'id' : IDL.Nat,
    'repeatDays' : IDL.Vec(Day),
    'verificationMode' : VerificationMode,
    'time' : Time,
    'enabled' : IDL.Bool,
    'sound' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'totalSuccesses' : IDL.Nat,
    'lastSuccessDate' : Time,
    'currentStreak' : IDL.Nat,
    'totalAlarmsTriggered' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAlarm' : IDL.Func(
        [Time, IDL.Vec(Day), VerificationMode, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAlarm' : IDL.Func([IDL.Nat], [], []),
    'getAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
    'getStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
    'updateAlarm' : IDL.Func(
        [IDL.Nat, Time, IDL.Vec(Day), VerificationMode, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };