/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alarm {
  'id' : bigint,
  'repeatDays' : Array<Day>,
  'verificationMode' : VerificationMode,
  'time' : Time,
  'enabled' : boolean,
  'sound' : string,
}
export type Day = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export type Time = bigint;
export interface UserStats {
  'totalSuccesses' : bigint,
  'lastSuccessDate' : Time,
  'currentStreak' : bigint,
  'totalAlarmsTriggered' : bigint,
}
export type VerificationMode = { 'mathPuzzle' : null } |
  { 'selfie' : null } |
  { 'voicePrompt' : null };
export interface _SERVICE {
  'createAlarm' : ActorMethod<
    [Time, Array<Day>, VerificationMode, string],
    bigint
  >,
  'deleteAlarm' : ActorMethod<[bigint], undefined>,
  'getAlarms' : ActorMethod<[], Array<Alarm>>,
  'getStats' : ActorMethod<[], [] | [UserStats]>,
  'updateAlarm' : ActorMethod<
    [bigint, Time, Array<Day>, VerificationMode, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];