/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Alarm {
    id: bigint;
    repeatDays: Array<Day>;
    verificationMode: VerificationMode;
    time: Time;
    enabled: boolean;
    sound: string;
}
export type Time = bigint;
export interface UserStats {
    totalSuccesses: bigint;
    lastSuccessDate: Time;
    currentStreak: bigint;
    totalAlarmsTriggered: bigint;
}
export enum Day {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum VerificationMode {
    mathPuzzle = "mathPuzzle",
    selfie = "selfie",
    voicePrompt = "voicePrompt"
}
export interface backendInterface {
    createAlarm(time: Time, repeatDays: Array<Day>, verificationMode: VerificationMode, sound: string): Promise<bigint>;
    deleteAlarm(alarmId: bigint): Promise<void>;
    getAlarms(): Promise<Array<Alarm>>;
    getStats(): Promise<UserStats | null>;
    updateAlarm(alarmId: bigint, time: Time, repeatDays: Array<Day>, verificationMode: VerificationMode, sound: string, enabled: boolean): Promise<void>;
}
import type { Alarm as _Alarm, Day as _Day, Time as _Time, UserStats as _UserStats, VerificationMode as _VerificationMode } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAlarm(arg0: Time, arg1: Array<Day>, arg2: VerificationMode, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlarm(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_VerificationMode_n4(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlarm(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), to_candid_VerificationMode_n4(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteAlarm(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlarm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlarm(arg0);
            return result;
        }
    }
    async getAlarms(): Promise<Array<Alarm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlarms();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlarms();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<UserStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAlarm(arg0: bigint, arg1: Time, arg2: Array<Day>, arg3: VerificationMode, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlarm(arg0, arg1, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), to_candid_VerificationMode_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlarm(arg0, arg1, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg2), to_candid_VerificationMode_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_Alarm_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alarm): Alarm {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Day_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationMode): VerificationMode {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStats]): UserStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    repeatDays: Array<_Day>;
    verificationMode: _VerificationMode;
    time: _Time;
    enabled: boolean;
    sound: string;
}): {
    id: bigint;
    repeatDays: Array<Day>;
    verificationMode: VerificationMode;
    time: Time;
    enabled: boolean;
    sound: string;
} {
    return {
        id: value.id,
        repeatDays: from_candid_vec_n9(_uploadFile, _downloadFile, value.repeatDays),
        verificationMode: from_candid_VerificationMode_n12(_uploadFile, _downloadFile, value.verificationMode),
        time: value.time,
        enabled: value.enabled,
        sound: value.sound
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): Day {
    return "tuesday" in value ? Day.tuesday : "wednesday" in value ? Day.wednesday : "saturday" in value ? Day.saturday : "thursday" in value ? Day.thursday : "sunday" in value ? Day.sunday : "friday" in value ? Day.friday : "monday" in value ? Day.monday : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mathPuzzle: null;
} | {
    selfie: null;
} | {
    voicePrompt: null;
}): VerificationMode {
    return "mathPuzzle" in value ? VerificationMode.mathPuzzle : "selfie" in value ? VerificationMode.selfie : "voicePrompt" in value ? VerificationMode.voicePrompt : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alarm>): Array<Alarm> {
    return value.map((x)=>from_candid_Alarm_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Day>): Array<Day> {
    return value.map((x)=>from_candid_Day_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Day_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): _Day {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationMode_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationMode): _VerificationMode {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == Day.tuesday ? {
        tuesday: null
    } : value == Day.wednesday ? {
        wednesday: null
    } : value == Day.saturday ? {
        saturday: null
    } : value == Day.thursday ? {
        thursday: null
    } : value == Day.sunday ? {
        sunday: null
    } : value == Day.friday ? {
        friday: null
    } : value == Day.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationMode): {
    mathPuzzle: null;
} | {
    selfie: null;
} | {
    voicePrompt: null;
} {
    return value == VerificationMode.mathPuzzle ? {
        mathPuzzle: null
    } : value == VerificationMode.selfie ? {
        selfie: null
    } : value == VerificationMode.voicePrompt ? {
        voicePrompt: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Day>): Array<_Day> {
    return value.map((x)=>to_candid_Day_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
